# Generated by Django 3.0.5 on 2021-05-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210504_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('date_naissance', models.DateField()),
                ('telephone', models.IntegerField()),
                ('ville', models.CharField(max_length=20)),
                ('name_pere', models.CharField(max_length=20)),
                ('name_mere', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=20)),
                ('institution', models.CharField(max_length=20)),
                ('fillier', models.CharField(max_length=20)),
                ('batch', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('telephone_mere', models.IntegerField()),
                ('telephone_pere', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='ForUser',
        ),
    ]
