# Generated by Django 3.0.5 on 2021-05-08 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210504_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotesUniversity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], max_length=20)),
                ('sem', models.CharField(choices=[('sem1', 'SEMESTER 1'), ('sem2', 'SEMESTER 2')], max_length=20)),
                ('matiere', models.CharField(max_length=150)),
                ('notes', models.CharField(max_length=150)),
                ('characteristic', models.CharField(choices=[('Academic', 'Academic'), ('Dine', 'Dine')], max_length=20)),
                ('moyen', models.IntegerField()),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.University')),
            ],
        ),
    ]
