# Generated by Django 3.0.5 on 2021-05-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_notesuniversity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='university',
            name='batch',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='university',
            name='designation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='university',
            name='fillier',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='university',
            name='institution',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='university',
            name='name_mere',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='university',
            name='name_pere',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='university',
            name='ville',
            field=models.CharField(max_length=100),
        ),
    ]
