# Generated by Django 3.0.5 on 2021-05-09 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210508_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='designation',
            field=models.CharField(choices=[('university', 'Etudiant Universitair'), ('Jeunne garcons', 'Jeunne Garcons'), ('Jeunne fille', 'Jeunne fille'), ('Petit garcons', 'Petit Garcons'), ('Petite fille', 'Petite fille'), ('Crash course', 'Crash course')], max_length=100),
        ),
    ]
