# Generated by Django 3.0.5 on 2021-05-11 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210511_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
