# Generated by Django 3.0.5 on 2021-05-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210511_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='designation',
            field=models.CharField(choices=[('university', 'Etudiant Universitair'), ('Jeunne garcons', 'Jeunne Garcons')], max_length=100),
        ),
    ]
