# Generated by Django 3.0.5 on 2021-05-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210513_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='designation',
        ),
        migrations.AddField(
            model_name='university',
            name='imageprofile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
