# Generated by Django 3.0.5 on 2021-05-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210513_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='imageprofile',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
