# Generated by Django 3.0.5 on 2021-05-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210513_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='designation',
            field=models.CharField(choices=[('university', 'Etudiant Universitair'), ('Jeunne garcons', 'Jeunne Garcons')], default='university', max_length=100),
        ),
    ]
