# Generated by Django 3.0.5 on 2021-05-15 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210513_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jeunes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('ville', models.CharField(max_length=100)),
                ('name_pere', models.CharField(max_length=100)),
                ('name_mere', models.CharField(max_length=100)),
                ('designation', models.CharField(default='Jeunes', max_length=100)),
                ('imageprofile', models.ImageField(blank=True, default='images/avatar.jpg', null=True, upload_to='images/')),
                ('institution', models.CharField(max_length=100)),
                ('fillier', models.CharField(max_length=100)),
                ('batch', models.CharField(choices=[('6 eme', '6 eme'), ('5 eme', '5 eme'), ('4 eme', '4 eme'), ('3 eme', '3 eme'), ('Second', 'Second'), ('Premiere', 'Premiere'), ('Terminal', 'Terminal')], default='6 eme', max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('telephone_mere', models.IntegerField()),
                ('telephone_pere', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='university',
            name='imageprofile',
            field=models.ImageField(blank=True, default='images/avatar.jpg', null=True, upload_to='images/'),
        ),
        migrations.CreateModel(
            name='NotesJeunes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], default='2021', max_length=20)),
                ('sem', models.CharField(choices=[('sem1', 'SEMESTER 1'), ('sem2', 'SEMESTER 2')], default='sem1', max_length=20)),
                ('matiere', models.CharField(max_length=150)),
                ('notes', models.CharField(max_length=150)),
                ('characteristic', models.CharField(choices=[('Academic', 'Academic'), ('Dine', 'Dine')], default='Academic', max_length=20)),
                ('moyen', models.IntegerField()),
                ('jeunes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Jeunes')),
            ],
        ),
    ]
