# Generated by Django 3.0.5 on 2021-05-15 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210515_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jeunes',
            name='fillier',
        ),
    ]
