# Generated by Django 3.0.5 on 2021-05-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_jeunes_fillier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeunes',
            name='batch',
            field=models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3'), ('T4', 'T4'), ('T5', 'T5'), ('6 eme', '6 eme'), ('5 eme', '5 eme'), ('4 eme', '4 eme'), ('3 eme', '3 eme'), ('Second', 'Second'), ('Premiere', 'Premiere'), ('Terminal', 'Terminal')], default='6 eme', max_length=100),
        ),
    ]
