# Generated by Django 3.0.5 on 2021-05-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210515_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeunes',
            name='designation',
            field=models.CharField(choices=[('Jeunne garcons', 'Jeunne Garcons'), ('Jeunne fille', 'Jeunne Fille'), ('Petit garcons', 'Petit Garcons'), ('Petite fille', 'Petite Fille')], default='Jeunes', max_length=100),
        ),
        migrations.AlterField(
            model_name='jeunes',
            name='institution',
            field=models.CharField(default='La Sagesse', max_length=100),
        ),
        migrations.AlterField(
            model_name='notesjeunes',
            name='sem',
            field=models.CharField(choices=[('sem1', 'SEMESTER 1'), ('sem2', 'SEMESTER 2'), ('sem3', 'SEMESTER 3')], default='sem1', max_length=20),
        ),
    ]
